// <auto-generated />
using System;
using GalloTracking.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GalloTracking.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("GalloTracking.Api.Domain.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RotaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("GalloTracking.Api.Domain.Localizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdLocal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precisao")
                        .HasColumnType("REAL");

                    b.Property<int>("RotaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampGps")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampRecebimento")
                        .HasColumnType("TEXT");

                    b.Property<double>("Velocidade")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.HasIndex("MotoristaId", "IdLocal")
                        .IsUnique();

                    b.ToTable("Localizacoes");
                });

            modelBuilder.Entity("GalloTracking.Api.Domain.Motorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Motoristas");
                });

            modelBuilder.Entity("GalloTracking.Api.Domain.Rota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaId");

                    b.ToTable("Rotas");
                });

            modelBuilder.Entity("GalloTracking.Api.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GalloTracking.Api.Domain.Entrega", b =>
                {
                    b.HasOne("GalloTracking.Api.Domain.Rota", "Rota")
                        .WithMany("Entregas")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("GalloTracking.Api.Domain.Localizacao", b =>
                {
                    b.HasOne("GalloTracking.Api.Domain.Rota", "Rota")
                        .WithMany("Localizacoes")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("GalloTracking.Api.Domain.Motorista", b =>
                {
                    b.HasOne("GalloTracking.Api.Domain.Usuario", "Usuario")
                        .WithOne("Motorista")
                        .HasForeignKey("GalloTracking.Api.Domain.Motorista", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GalloTracking.Api.Domain.Rota", b =>
                {
                    b.HasOne("GalloTracking.Api.Domain.Motorista", "Motorista")
                        .WithMany("Rotas")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motorista");
                });

            modelBuilder.Entity("GalloTracking.Api.Domain.Motorista", b =>
                {
                    b.Navigation("Rotas");
                });

            modelBuilder.Entity("GalloTracking.Api.Domain.Rota", b =>
                {
                    b.Navigation("Entregas");

                    b.Navigation("Localizacoes");
                });

            modelBuilder.Entity("GalloTracking.Api.Domain.Usuario", b =>
                {
                    b.Navigation("Motorista");
                });
#pragma warning restore 612, 618
        }
    }
}
